import React, { useEffect } from 'react'
// import styles from './index.module.css'
import Header from './Header'
import Head from 'next/head';
import type { LayoutProps } from '../../../../types/pageWithLayout'
import { fetchBooks } from '@/features/productsSlice'
import { useAppDispatch, useAppSelector } from '@/store'

interface Props {
    children: React.ReactNode;
}

const index : LayoutProps = ({ children }: Props) => {
    const dispatch = useAppDispatch()
    const {loading, error} = useAppSelector((state) => state.products)

    useEffect(() => {
        dispatch(fetchBooks());
    }, []);
    return (
        <>
            <Head>
                <title>Book Store</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="px-[60px] py-10">
                {children}
            </main>
        </>
    )
}

export default index