import React from 'react'
// import styles from './index.module.css'
import Head from 'next/head';
import Image from 'next/image';
import styles from './index.module.css'

interface Props {
    children: React.ReactNode;
}

const index = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>Book Store Welcome</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <div className={styles.image}>

                </div>
                <main className={styles.main}>
                    {children}
                </main>
            </div>
        </>
    )
}

export default index